### ISSUE TITLE
修复维基媒体

### ISSUE THREAD

**Issue by Xihihhh** [URenko/Accesser#143]
维基媒体新IP:185.15.58/59.224，除了upload.wikimedia.org是185.15.58/59.240

配置：
pac:
```javascript
var domains = {
  "mediawiki.org": 1,
  "wikipedia.org": 1,
  "wikimedia.org": 1,
  "wikiquote.org": 1,
  "wikinews.org": 1,
  "wikiversity.org": 1,
  "wiktionary.org": 1,
  "wikibooks.org": 1,
  "wikivoyage.org": 1,
  "wikisource.org": 1,
  "wikidata.org": 1,
  "wikifunctions.org": 1
}
```
config.toml:
```toml
[hosts]
"mediawiki.org" = "185.15.58.224"
".mediawiki.org" = "185.15.58.224"
"wikipedia.org" = "185.15.58.224"
".wikipedia.org" = "185.15.58.224"
"upload.wikimedia.org" = "185.15.58.240"
"wikimedia.org" = "185.15.58.224"
".wikimedia.org" = "185.15.58.224"
"wikiquote.org" = "185.15.58.224"
".wikiquote.org" = "185.15.58.224"
"wikinews.org" = "185.15.58.224"
".wikinews.org" = "185.15.58.224"
"wikiversity.org" = "185.15.58.224"
".wikiversity.org" = "185.15.58.224"
"wiktionary.org" = "185.15.58.224"
".wiktionary.org" = "185.15.58.224"
"wikibooks.org" = "185.15.58.224"
".wikibooks.org" = "185.15.58.224"
"wikisource.org" = "185.15.58.224"
".wikisource.org" = "185.15.58.224"
"wikidata.org" = "185.15.58.224"
".wikidata.org" = "185.15.58.224"
"wikifunctions.org" = "185.15.58.224"
".wikifunctions.org" = "185.15.58.224"
"wikivoyage.org" = "185.15.58.224"
".wikivoyage.org" = "185.15.58.224"
```
